### ISSUE TITLE
error bad address github.com en webdav

### ISSUE THREAD

**Issue by xabiliza** [atareao/self-hosted#25]
Hola,
cuando lanzo el contenedor  junto con caddy me sale el siguiente error:
wget: bad address 'github.com'
he revisado las direcciones del dockerfile y no hay ningun problema. alguna sugerencia?
gracias de antemano

**Comment by atareao** [comment]
Hola, 
Con GitHub.com? Cuando te da ese error?
Gracias

**Comment by xabiliza** [comment]
pues parece que se ha resuelto. el error me salia cuando lanzaba los docker compose:
`docker-compose -f docker-compose.yml -f docker-compose.caddy.yml up -d`. 
se paraba y marcaba en rojo el error "error bad address github.com".
ahora me ha funcionado correctamente.
gracias por el interes.
